#!/bin/bash 
#check if the antkorp is already running and if the directory is there 
#then stop all antkorp services.
if [ -f "/etc/init/antkorp.conf" ]; then
	echo "stopping all antkorp services.";
	initctl stop antkorp
	rc=$?
	if [[ $rc != 0 ]] ; then
	    echo "stopping antkorp platform failed with:" $rc;
	    exit $rc
	fi
else
	#if there is antkorp already running no need to create the user again.
	echo "Creating Neptunium user and group.";
	useradd -M antkorp
	rc=$?
	if [[ $rc != 0 ]] ; then
	    echo "creating antkorp user & group failed with:" $rc;
	    exit $rc
	fi
	echo "Creating Neptunium home directory.";
    mkdir -p /home/antkorp 
    chown -R antkorp:antkorp /home/antkorp
fi
exit 0;
